### ISSUE TITLE
Releasing a new version with Django 4.2 support

### ISSUE THREAD

**Issue by irtazaakram** [django/django-contrib-comments#193]
When can we expect the release of the new version with Django 4.2, considering that the master branch has already been updated?

Thanks,

**Comment by carltongibson** [comment]
@irtazaakram Please stop spamming multiple projects with these comments. **ALL** you're talking about here is releasing a package with the updated Trove classifier on PyPI, since the packages have no significant changes needed for 4.2 compatibility. 

**If you want to help** make the PR adding the Trove classifier and preparing the release, rather than pressuring volunteer maintainers into doing work to satisfy your corporate priorities.
